---
title: "2014毕业论文"
author: "qiufei"
date: "2017年11月8日"
bibliography: ref.bib
output: 
  word_document: 
    toc: yes
  html_document: 
    df_print: kable
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 资料搜集

# 论文框架

## 中小机构对服务中小客户更有优势吗？以银行业为例 

<!-- 2014010309 陆怡婷  -->

传统的观点认为中小金融机构比大型机构机构在服务中小客户上更有优势。

以上观点成立的一个前提条件是，大型机构在资金来源成本上低成本的优势不能抵消其在机构运营上高成本的劣势。但是如果在一种经济环境中，机构的运营模式是趋同的，都是一种粗放低成本的方式，那么小型机构在运营上的低成本优势就不会那么明显，于是大型机构在资金成本上的优势在竞争中就显得更加凸出。

中国的金融机构一直有粗放经营的传统，特别是银行，被批评只会收抵押放贷款。在这种业务经营模式比较简单的情况下，大机构可能业务向中小客户拓展，可能也增加不了多少运营费用。


验证的思路：

1. 比较大银行和小银行的中小客户业务条线的运营费用的差异。零售业务条线可以用来近似代替中小客户业务条线。（这个可以再讨论，在文献阅读中可以进一步补充。）

2. 比较大型银行和小型银行子在融资成本上的差异。比如存款利率，贴现利率等。

3. 比较以上两大差异，如果大银行在融资成本上的优势差异大于小银行在运用费用上的优势差异，我们就认为中小机构在服务中小客户上没有更多的优势。

## 关于并购绩效的评价方法 

<!-- 2014010593  方涛  -->

## 中美两国股市名义价格水平的对比研究 

<!-- 2014011060  王锦浩  -->




有研究表明美国自大萧条开始至今，物价上涨了10倍多，然而美国股票的名义平均价格一直保持在35美元上[@Weld2009]。

这是一个比较有趣的现象，对此，我们可以研究下中国自股市开始运行以来的股票平均价格是多少，看一下中国的股票平均价是否也是多年维持不变。

如果中国的股价平均数也是多年维持不变的话，比较下两国股票平均价格多年不变的原因。如果中国变的话，可以分析下为什么中国变，而美国不变。

选这个题目是因为今年行为经济学比较热门（今年的诺贝尔经济学奖就是颁发给行为经济学领域的学者的），美国的名义平均股价维持不变可能是一种习惯，美国人认为当一般股票的股价到70美元一股的时候，可能就显得太高了，于是就会分拆股票，于是股价维持在35美元附近。这种习惯就是一种心理因素，可以用行为经济学的东西来分析。


## 金融部门规模与经济增长质量关系研究 

<!-- 2014011082 王雅迪  -->


金融部门规模与经济增长质量之间的桥梁是金融部门的职能。

如果金融部门职能发挥得好，那么就会促进经济增长；如果金融部门只能发挥得不好，那么就会带来破坏经济增长。

金融部门的核心职能是动员资金、风险定价

## 央行资产负债表规模与企业融资成本关系研究 

<!-- 2014011103 郑雯  -->

## 从资金流量表看中国金融系统结构的变化 

<!-- 2014011454  涂铭杭  -->

## 金融部门竞争与社会福利关系研究 

<!-- 2014012935 陈翔宇  -->

## 商业银行信用卡风险管理研究 

<!-- 2014014171  包从赶  -->


--
参考文献：

